### ISSUE TITLE
Документирующие комментарии ломают компоненту

### ISSUE THREAD

**Issue by igostv** [Sebekerga/native_api_1c#10]
Документирующие комментарии `///` ломают компоненту из примера
https://github.com/Sebekerga/native_api_1c/blob/a4e569d67cda7e0ce8fd7c54f162b047a29d6ad9/sample_addin_rs/src/lib.rs#L12-L14

Компонента собирается, но нет ни свойств, ни методов
![image](https://github.com/Sebekerga/native_api_1c/assets/15666182/88e1290b-7a35-445c-a233-d91a72a4ce5a)

Если `///` заменить на `//` то и свойства, и методы есть.
![image](https://github.com/Sebekerga/native_api_1c/assets/15666182/26ca6737-26f3-43dd-ba35-071f8b5961d1)

**Comment by Sebekerga** [comment]
Исправил в b66a6c835ffd88096016489846d2c8b998ebadd1
