### ISSUE TITLE
Текст XML содержит недопустимый символ 

### ISSUE THREAD

**Issue by Gopsat** [Sebekerga/native_api_1c#13]
В windows если метод компоненты возвращает строку и эту строку попробовать передать с сервера или на сервер , платформа выдает ошибку: Текст XML содержит недопустимый символ в позиции 17.

**Comment by Sebekerga** [comment]
Можно, пожалуйста, побольше информации? Как выглядит строка? Скорее всего дубликат #5, эти изменения еще не попали на crates.io, но они есть в репозитории

**Comment by Sebekerga** [comment]
[v0.10.6](https://github.com/Sebekerga/native_api_1c/tree/v0.10.6) теперь на crates.io, можете пробовать его - если проблема остается, пожвлуйста, делитесь информацией

**Comment by Gopsat** [comment]
Спасибо.  Исправление же в native_api_1c_core?  Хотел обновить native_api_1c_core  `cargo add native_api_1c_core` выдаёт ошибку:

 __cargo add native_api_1c
    Updating crates.io index
      Adding native_api_1c v0.10.6 to dependencies.
             Features:
             + macro
    Updating crates.io index
error: failed to select a version for `native_api_1c_core`.
    ... required by package `native_api_1c v0.10.6`
    ... which satisfies dependency `native_api_1c = "^0.10.6"` of package `searchImageLib v0.1.0 (E:\rust\)`
versions that meet the requirements `=0.9.3` are: 0.9.3

all possible versions conflict with previously selected packages.

  previously selected package `native_api_1c_core v0.9.4`
    ... which satisfies dependency `native_api_1c_core = "^0.9.4"` of package `searchImageLib v0.1.0 (E:\rust\)`

failed to select a version for `native_api_1c_core` which could resolve thi_s conflict_

**Comment by Sebekerga** [comment]
Поделитесь, пожалуйста, разделом `[dependencies]` в вашем `Cargo.toml`

**Comment by Gopsat** [comment]
Если не добавлять в зависимости native_api_1c_core то обращается к версии native_api_1c_core 0.9.3 и ошибка в 1с тоже выходит.

**Comment by Gopsat** [comment]
Может здесь зависимость поменять нужно? на 0.9.4
![image](https://github.com/Sebekerga/native_api_1c/assets/54476735/c561d50d-839c-4b0d-b25e-6f07aa74bce8)

**Comment by Sebekerga** [comment]
Перенес изменения по версиям из dev ветки, можете пробовать пользоваться через `native_api_1c = { git = "https://github.com/Sebekerga/native_api_1c" }`

**Comment by Gopsat** [comment]
![image](https://github.com/Sebekerga/native_api_1c/assets/54476735/6eb4142a-ff34-4367-9c47-6587d7aa6b26)
![image](https://github.com/Sebekerga/native_api_1c/assets/54476735/fd1ed7d9-c43a-4c35-9f09-041988cf33a4)

Всё равно возвращает почему то совсем пустую строку.
Мой метод возвращает вот это:
`Ok("".to_string())`

**Comment by Gopsat** [comment]
![image](https://github.com/Sebekerga/native_api_1c/assets/54476735/49e48b70-9533-4e19-ab22-3bae3d7f7593)

**Comment by Sebekerga** [comment]
Окей, я увидел в чем проблема, сори что запутал, этот комит не приехал в main :(

**Comment by Sebekerga** [comment]
Исправил, доступно здесь, из dev ветки: 
```toml
[dependencies]
native_api_1c = { git = "https://github.com/Sebekerga/native_api_1c", tag = "fixed_windows_nil" }
```

Единственное, вам нужно будет добавить в описании параметров "`ty = Type`", например%:
```rust
#[add_in_func(name = "TransformString", name_ru = "ПреобразоватьСтроку")]
#[arg(ty = Str, as_in)]
#[arg(ty = Str, as_out)]
#[returns(ty = Bool)]
transform_str: fn(&Self, String, &mut String) -> bool
```

Такой вид скоро будет в основной ветке.

**Comment by Gopsat** [comment]
Спасибо. Сейчас код выполняется.
