### ISSUE TITLE
Вылетает из 1с

### ISSUE THREAD

**Issue by Gopsat** [Sebekerga/native_api_1c#14]
После выполнения функции через 5 секунд где то 1с вылетает без ошибок.  Протестировал на двух разных серверах windows. Где выполняется код тоже не важно, вылетает на клиенте и на сервере. Окно 1с предприятия просто закрывается

**Comment by Sebekerga** [comment]
Это не обязательно ошибка компоненты, убедитесь, что ваш код нигде не "паникует" - уберите все `unwrap()` и непосредственные `panic!()`
