### ISSUE TITLE
[dev] Перестал работать возвращаемый тип None

### ISSUE THREAD

**Issue by igostv** [Sebekerga/native_api_1c#15]
В dev ветке что-то поломалось, нельзя задать возвращаемый тип None
`#[returns(ty = None, result)]`

```bash
error: unknown type `None`. Must be one of: Bool, Int, Float, Str, Date, Blob, None
  --> src\lib.rs:24:15
   |
24 |     #[returns(ty = None, result)]
   |               ^^
```

**Comment by Sebekerga** [comment]
Я сейчас привожу в порядок структуру макро крейта и перевожу все на darling, и syn::parse, где получается, поэтому будут ломающие изменения - постараюсь починить как можно быстрее :)

**Comment by igostv** [comment]
Исправлено в e558b26dd780fcb541f8c734afc983bcbe19816a
