### ISSUE TITLE
Проблема на Линукс

### ISSUE THREAD

**Issue by AleksandrSmith7** [Sebekerga/native_api_1c#3]
![Снимок экрана от 2023-08-31 10-21-17](https://github.com/Sebekerga/native_api_1c/assets/143295468/786de9c3-e743-43ff-9acf-da8716533008)
Добрый день на Линукс так и не хочет работать библиотека, не могу понять в чем дело. Ubuntu 22.04.3 LTS
Тестил на платформе для Линукс. 1С:Предприятие 8.3, учебная версия (8.3.23.1688)
&НаКлиенте
Процедура НаписатьСообщение(Команда)
	Попытка
	    НачатьУстановкуВнешнейКомпоненты(,"ОбщийМакет.VK");
		Сообщить("ОК");  
		Исключение
		Сообщить("Нет")
	КонецПопытки;  
	ПодключитьВнешнююКомпонентуАсинх("ОбщийМакет.VK","Test2",ТипВнешнейКомпоненты.Native);
	ВК= Новый("AddIn.Test2.Test2");
	Результат = ВК.ОбработатьДанные("Тел","ФИО");
	Сообщить (Результат);
КонецПроцедуры
Результат на скриншоте
Описание ошибки: 
Тип не определен (AddIn.Test2.Test2)
{Документ.СвязьСКлиентом.Форма.ФормаДокумента.Форма(26)}:ВК= Новый("AddIn.Test2.Test2");

[ОшибкаВоВремяВыполненияВстроенногоЯзыка, ОшибкаИспользованияВстроенногоЯзыка]

Тестовый код

use std::{ 
   // fs::{metadata, File}, 
   // io::Read, 
    sync::Arc, 
}; 
use native_api_1c::{
    native_api_1c_core::ffi::connection::Connection, 
    native_api_1c_macro::AddIn
}; 

#[derive(AddIn)] 
pub struct Test2 { 
    #[add_in_con] // соединение с 1С для вызова внешних событий 
    connection: Arc<Option<&'static Connection>>, // Arc для возможности многопоточности 

    #[add_in_func(name = "Test2", name_ru = "ОбработатьДанные")] 
    #[arg(Str)]
    #[arg(Str)] 
    #[returns(Str, result)] 
    read_bytes: fn(&Self, String, String) -> Result<String, Box<dyn std::error::Error>>, 
} 

impl Test2 { 
    pub fn new() -> Self { 
        Self { connection: Arc::new(None), 
        read_bytes: Self::read_bytes, } 
    } 

    pub fn read_bytes(&self, imya: String, telefon: String) -> Result<String, Box<dyn std::error::Error>> { 
        let k=" Взаимодействие раст и 1С работает".to_string();
        let f=imya+&telefon+&k;
        Ok(f) 
    } 
}

**Comment by Sebekerga** [comment]
Два момента:
1) Обверните пж в кодовые блоки, а то читается тяжело. [Пример](https://ru.markdown.net.br/rasshirennyy-sintaksis/#fenced-code-block)
2) Можете так же приложить ваш файл `Cargo.toml`
3) И результат команды `cargo expand > expand.rs` (сохранится в файл `expand.rs`)

По возможности так же кидайте длинный файлы под спойлер. Пример:

````
<details>
  <summary>Кодовый блок под сполйером</summary>
  Описание
  
  ```rust
  "Ваш длинный кусок кода"
  ```
</details>
````

**Comment by Sebekerga** [comment]
![image](https://github.com/Sebekerga/native_api_1c/assets/16242246/38a01939-8e7a-432c-93b6-861d91109bd5)

У меня вроде б завелся ваш код, хотя обращаться по имени процедуры "ОбработатьДанные" получается почему-то через раз, но в любом случае, у вас ошибка не в этом. Поэтому будем смотреть дальше

**Comment by AleksandrSmith7** [comment]
[Файлы для разбора.zip](https://github.com/Sebekerga/native_api_1c/files/12485158/default.zip)
Добавил все файлы в архив. Если хотите могу предоставить Анидеск например.
Спасибо за замечания, учту, я на гит новичок.

**Comment by AleksandrSmith7** [comment]
Все оказалось проще чем я думал
![image](https://github.com/Sebekerga/native_api_1c/assets/143295468/9649a04c-0cd1-49b7-a642-3b336cb01ad9)
Нужно было включить режим синхронных использования вызовов в конфигурации. Спасибо за помощь) Работает все на Линукс.

**Comment by Sebekerga** [comment]
Отлично
