### ISSUE TITLE
Пустая строка не пустая (null terminator)

### ISSUE THREAD

**Issue by Toveal** [Sebekerga/native_api_1c#5]
Здравствуйте. Написал простую компоненту в качестве примера. Получаю пустую строку, проверяю в 1С на пустую строку, но она не является пустой строкой

Код Rust:
```rust
use std::sync::Arc;

use native_api_1c::{native_api_1c_core::ffi::connection::Connection, native_api_1c_macro::AddIn};

#[derive(AddIn)]
pub struct TestStr {
    #[add_in_con]
    connection: Arc<Option<&'static Connection>>,

    #[add_in_func(name = "GetEmptyString", name_ru = "ПолучитьПустуюСтроку")]
    #[returns(Str)]
    pub get_empty_string: fn(&Self) -> String,
}

impl TestStr {
    pub fn new() -> Self {
        Self {
            connection: Arc::new(None),
            get_empty_string: Self::get_empty_string,
        }
    }

    pub fn get_empty_string(&self) -> String {
        "".to_string()
    }
}
```
Код 1С:
```bsl
УстановитьВнешнююКомпоненту("ОбщийМакет.Testik");
ВК = ПодключитьВнешнююКомпоненту("ОбщийМакет.Testik", "Testik", ТипВнешнейКомпоненты.Native);
ВК = Новый("AddIn.Testik.TestStr"); 
	                  
ПростоПустаяСтрока = ВК.ПолучитьПустуюСтроку();

Если ПростоПустаяСтрока = "" Тогда
    Сообщить("Пустая строка реально пустая!");
Иначе
    Сообщить("Пустая строка не пустая? Хмм");
КонецЕсли;
```

Используется библиотека с GitHub. Версия 0.10.5
```toml
[dependencies]
native_api_1c = { git = "https://github.com/Sebekerga/native_api_1c" }
```

**Comment by Sebekerga** [comment]
- Пожалуйста, укажите ОС
- Что выдает `ТипЗнч(ПростоПустаяСтрока)`? И если там строка, то какая?

Посмотрю попожже, спасибо за репорт

**Comment by Toveal** [comment]
- ОС - Windows 10 22H2
- 1С выдает тип "Строка"

Значение:
![image](https://github.com/Sebekerga/native_api_1c/assets/130573286/505cda99-5e93-4d0f-9dfc-6d0c6df38606)

Заметил одну особенность. Если значение переменной "ПростоПустаяСтрока" поместить в ТекстовыйДокумент (УстановитьТекст) и получить обратно (ПолучитьТекст) то проверка на пустую строку работает

```bsl
УстановитьВнешнююКомпоненту("ОбщийМакет.FBReader");
ВК = ПодключитьВнешнююКомпоненту("ОбщийМакет.FBReader", "FBReader", ТипВнешнейКомпоненты.Native);
ВК = Новый("AddIn.FBReader.TestStr"); 

ПростоПустаяСтрока = ВК.ПолучитьПустуюСтроку();

Если ПростоПустаяСтрока = "" Тогда
	Сообщить("Пустая строка реально пустая!");
Иначе
	Сообщить("Пустая строка не пустая? Хмм");
КонецЕсли;

ТекстФайл = Новый ТекстовыйДокумент;
ТекстФайл.УстановитьТекст(ПростоПустаяСтрока);

НоваяПустаяСтрока = Текстфайл.ПолучитьТекст();

Если НоваяПустаяСтрока = "" Тогда
	Сообщить("После текстового документа работает");
Иначе
	Сообщить("После текстового документа не работает");
КонецЕсли;
```

**Comment by Toveal** [comment]
Выяснил что это пустой символ (код 0 в Unicode)
И вот такой код отработает

```bsl
УстановитьВнешнююКомпоненту("ОбщийМакет.FBReader");
ВК = ПодключитьВнешнююКомпоненту("ОбщийМакет.FBReader", "FBReader", ТипВнешнейКомпоненты.Native);
ВК = Новый("AddIn.FBReader.TestStr"); 

ПростоПустаяСтрока = ВК.ПолучитьПустуюСтроку();

Если ПростоПустаяСтрока = Символ(0) Тогда
	Сообщить("Пустая строка реально пустая!");
Иначе
	Сообщить("Пустая строка не пустая? Хмм");
КонецЕсли;
```

**Comment by Sebekerga** [comment]
Попробовал под Linux, `ВК.ПолучитьПустуюСтроку() = ""`, странно. Я еще гляну на винде на днях. Пока можете еще дать инфы. Что выплюнет `СтрДлина(ВК.ПолучитьПустуюСтроку())`?

**Comment by Toveal** [comment]
> Попробовал под Linux, `ВК.ПолучитьПустуюСтроку() = ""` и `СтрДлина(ВК.ПолучитьПустуюСтроку()) = СтрДлина("")`, странно. Я еще гляну на винде на днях. Пока можете еще дать инфы? Что выплюнет `СтрДлина(ВК.ПолучитьПустуюСтроку())`?
> 
> Не могу код с линукса нормально скопипастить, к сожалению, т.к. у меня обучающая лицензия.

Выдает 1

**Comment by Toveal** [comment]
Кажется проблема в функции
native_api_1c_core::ffi::string_utils::os_string_nil (ветка windows)

А именно в chain(Some(0).into_iter())

Из-за этого мы получаем вместо пустой строки символ 0 и если написать строку в 1С (например "Привет") то "Привет" из компоненты не будет равен тому что написано в 1С

**Comment by Sebekerga** [comment]
Почти наверняка, что так. Если у вас есть возможность потестить, было бы здорово - я до конца недели не смогу уделить время.

**Comment by Sebekerga** [comment]
Попробовал, просто удалить чеин нуля не получиться. 

Нужно ноль чейнить, когда мы передаем в 1С имена функций и параметров, иначе не взлетает. Но ноль не нужно чейнить, когда мы передаем в 1С результаты функций. Надо сделать 2 метода, для уних систем он будет дублироваться.

**Comment by Sebekerga** [comment]
Данная ошибка была исправлена в [PR](https://github.com/Sebekerga/native_api_1c_macro/pull/3), пока что только в `dev` канале, на выходных, надеюсь, перенесу в основной и на crates.io
