### ISSUE TITLE
Ошибка повторного вызова метода на русском

### ISSUE THREAD

**Issue by WorldException** [Sebekerga/native_api_1c#8]
При повторном обращении не находится метод на русском языке.
Удалось исправить это поведение. 
Можно включить эти изменения в основную ветку?

https://github.com/WorldException/native_api_1c_macro/commit/9b1163589f7901e26eecadead45850d28fd35eaf

**Comment by Sebekerga** [comment]
Обсуждение здесь:
https://github.com/Sebekerga/native_api_1c_macro/pull/2

**Comment by WorldException** [comment]
Спасибо.
